apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: thiexco/my-app:fad3d217820c0f2aea44ce1a8ffec4cee2156222
        ports:
        - containerPort: 3000
