apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: thiexco/my-app:c1cf7d886f84236183837eeed306d7d4324018e8
        ports:
        - containerPort: 3000
