apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: thiexco/my-app:17b947c62fd2967a74ea15eb5d89073daa59386c
        ports:
        - containerPort: 3000
